services:
  selenium-webscraper:
    image: selenium/standalone-chrome
    ports: 
      - "4444:4444"
    depends_on:
      - flask_app
  flask_app:
    build:
      context: .
      dockerfile: flask_app.dockerfile
    ports:
      - "5000:5000"